<?php

namespace WPooW\Utilities;


class CONSTS
{
    CONST STATIC_PAGES_TYPE_PATH = 1;
    CONST STATIC_PAGES_TYPE_CONTENT = 2;
    
    CONST WP_AUTH_MANAGE_OPTIONS = "manage_options";

    CONST ELEMENT_PAGE_TYPE_SETTING_PAGE = 2 ;
    CONST ELEMENT_PAGE_TYPE_POSTTYPE_PAGE  = 1;

}


